# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# git status is so slow....
[git_status]
disabled = true

[kotlin]
disabled = true

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 6
truncation_symbol = ' ' # nf-fa-folder_open
truncate_to_repo = false
read_only = ' 󰌾 ' # nf-md-lock

# worktree -> 重いので一旦コメントアウト
# [custom.git_worktree]
# command = '''
# git worktree list --porcelain \
# | awk '
#   /^worktree / { wt=$2 }
#   /^branch / {
#     sub("refs/heads/", "", $2)
#     if (wt == "'"$PWD"'") {
#       print $2
#     }
#   }
# '
# '''
# when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1'
# format = '🌳 [$output]($style) '
# style = 'bold cyan'
