tap "homebrew/brew"
tap "homebrew/cask-fonts"

# CLI tools are managed via Nix/home-manager (see flake.nix).
# ghcup is a GHC installer/updater tool and doesn't fit Nix's package model,
# so it stays on Homebrew.
brew "ghcup"

cask "1password"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "alt-tab"
cask "arc"
cask "claude"
cask "deepl"
cask "devtoys"
cask "docker-desktop"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "fuwari"
cask "gcloud-cli"
cask "hammerspoon"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "licecap"
cask "notion"
cask "obsidian"
cask "raindropio"
cask "raycast"
cask "remnote"
cask "spotify"
cask "stats"
cask "thebrowsercompany-dia"
cask "ubersicht"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
cask "kindle"
