name: CI
on:
  push

jobs:
  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Install dotfiles
        run: .bin/setup.sh

  nix-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Check flake
        run: nix flake check --no-build
      - name: Build wsl home-manager configuration
        run: nix build --impure ".#homeConfigurations.wsl.activationPackage"
